### ISSUE TITLE
How to run tests on Travis CI?

### ISSUE THREAD

**Issue by nicklaw5** [SimulatedGREG/electron-vue#219]
***Note**: I'm working with the `dev` branch*

AppVeyor supports testing Electron apps out of the box which is great, but I'm having difficulty configuring Travis CI for headless testing. I've tried to follow [this tutorial](https://electron.atom.io/docs/tutorial/testing-on-headless-ci/), but when running `xvfb-maybe karma start test/unit/karma.conf.js` I'm getting the bellow error:

```bash
$ xvfb-maybe karma start test/unit/karma.conf.js
20 05 2017 08:47:19.166:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
20 05 2017 08:47:19.167:ERROR [preprocess]: Can not load "sourcemap", it is not registered!
  Perhaps you are missing some plugin?
/home/nick/.npm-global/lib/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:mocha"! (Resolving: framework:mocha)
    at error (/home/nick/.npm-global/lib/node_modules/karma/node_modules/di/lib/injector.js:22:12)
    at Object.get (/home/nick/.npm-global/lib/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at Injector.get (/home/nick/.npm-global/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /home/nick/.npm-global/lib/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at Server._start (/home/nick/.npm-global/lib/node_modules/karma/lib/server.js:142:21)
    at Injector.invoke (/home/nick/.npm-global/lib/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.start (/home/nick/.npm-global/lib/node_modules/karma/lib/server.js:103:18)
    at Object.exports.run (/home/nick/.npm-global/lib/node_modules/karma/lib/cli.js:280:26)
    at Object.<anonymous> (/home/nick/.npm-global/lib/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
Failed with exit code: 1
Output:
```

Some investigation led me to karma-runner/karma#2452, but I'm not sure if it relates. Has anyone managed to get tests running on Travis CI? Am I missing something?

**Comment by SimulatedGREG** [comment]
@nicklaw5 

Not sure if you are on a more recent version of the `dev` branch, but with the new included `appveyor.yml` file on the `electron-builder` configuration I was able to accomplish this very easily. Just adding the `yarn test` command to the build step was all I needed. 

[**appveyor.yml**](https://github.com/SimulatedGREG/electron-ci-test/blob/master/appveyor.yml#L25-L27)
```yml
build_script:
  - yarn test
  - yarn run build
```

Repository: https://github.com/SimulatedGREG/electron-ci-test
AppVeyor Build: https://ci.appveyor.com/project/SimulatedGREG/electron-ci-test

**Comment by nicklaw5** [comment]
I just forked the `dev` branch this morning, so I assuming I'm up to date.

Like I mentioned above, I can [successfully run the tests on AppVeyor](https://ci.appveyor.com/project/stryveapp/stryve/build/0.1.5) with no issues, but I can't accomplish the same on Travis CI.

Here's an example of running the tests WITHOUT `xvfb` configured:
https://travis-ci.org/stryveapp/stryve/builds/234179468

And here's an example of running the tests WITH `xvfb` configured:
https://travis-ci.org/stryveapp/stryve/builds/234172436

I would like to be able to have tests run on both AppVeyor and Travic CI platforms since my app will be cross platform compatible.

**Comment by SimulatedGREG** [comment]
@nicklaw5 

Following the instructions from the electron docs you posted above, I was able to accomplish Travis CI testing with this configuration...

[**.travis.yml**](https://github.com/SimulatedGREG/electron-ci-test/blob/master/.travis.yml#L21-L35)

```yml
addons:
  apt:
    packages:
    - xvfb
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- nvm install 7
- npm install -g yarn xvfb-maybe
- yarn
script:
- xvfb-maybe node_modules/.bin/karma start test/unit/karma.conf.js
- yarn run pack && xvfb-maybe node_modules/.bin/mocha test/e2e
```

macOS build: https://travis-ci.org/SimulatedGREG/electron-ci-test/jobs/234255885
linux build: https://travis-ci.org/SimulatedGREG/electron-ci-test/jobs/234255886

**Comment by nicklaw5** [comment]
Thanks for the help @SimulatedGREG, that worked perfectly!

For those that stumble across this in the future, here is the complete `.travis.yml` configuration:

```yml
osx_image: xcode8
sudo: required
dist: trusty
language: c
matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
cache:
  directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - xvfb
before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
    "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
    | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
install:
  - nvm install 7
  - npm install -g yarn xvfb-maybe
  - yarn
script:
  - yarn run build
  - xvfb-maybe node_modules/.bin/karma start test/unit/karma.conf.js
  - yarn run pack && xvfb-maybe node_modules/.bin/mocha test/e2e
```

**Comment by SimulatedGREG** [comment]
Here is the `appveyor.yml` just in case anyone else needs it as well.

```yml
version: 0.1.{build}

branches:
  only:
    - master

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - git reset --hard HEAD
  - npm install yarn -g
  - yarn
  - node --version

build_script:
  - yarn test
  - yarn run build

test: off
```
