### ISSUE TITLE
different css style between `npm run dev` and `npm run build`

### ISSUE THREAD

**Issue by fluency03** [SimulatedGREG/electron-vue#374]
## Describe the issue / bug.

I have a `input` element with the following css style:
```css
  .host-input {
    margin-left: 10px;
    display: inline-table;
    width: 300px;
  }
```

If I run `npm run dev`, the width is correct. 

However, if I run `npm run build` and open the generated app, the width of the `input` element is to the border of the right, which I think is `auto`.

How could this difference happen?  Is it related to the difference of two `webpack.renderer.config.js` files under the root dir and the `./electron-vue`?

I have the same issue with anchor element. 
```css
  a {
    color: inherit;
  }
```
In `dev` environment, it is with black color, however, after I open the `build` app, the color is blue. 

#### Under dev:

<img width="1009" alt="dev" src="https://user-images.githubusercontent.com/7440735/29780644-cfa4d0fc-8c16-11e7-8f03-280cec313f03.png">

#### After build:

<img width="1006" alt="build" src="https://user-images.githubusercontent.com/7440735/29780780-47ea6f40-8c17-11e7-82cd-a19bddef4104.png">

## Tell me about your development environment.
  * Node version: v7.7.4
  * NPM version: 4.1.2
  * vue-cli version: (if necessary)
  * Operating System: MacOS
