### ISSUE TITLE
keyboard shortcut, eval and webpack module 

### ISSUE THREAD

**Issue by simdax** [SimulatedGREG/electron-vue#548]
Hello Guys

I'm making an app, and I hitting a wall

I define a menu in which the click function is a string that I 'eval' after

```
- label: 'Edit'
  submenu:
    - role: 'undo'
    - role: 'redo'
- role: 'help'
  submenu:
    - label: 'connect'
      accelerator: 'CmdOrCtrl+u'
      click: "createWindow()"
      #click: "require('electron').shell.openExternal('https://electronjs.org')"

```

```
    if (k == "click")
	return function () {
	    eval(v)
	}
```

With the   #click: "require('electron').shell.openExternal('https://electronjs.org')", all works fine
but if my string refers to a module I imported, electron can't find it. I have to do some extra filtering, like
``` if ( v === 'createWindow()') createWindow() ```
which is a little redundant...

Someone would have a kind of answer for this problem

Thank you !
